#lang ivy1.7

type pcode_bits
interpret pcode_bits -> bv[8]
type cid
object nas_pdu_string = {
    type this = {0,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z} # 0 is error
}

object message_enum = {
    type this = {initial_message, successful_outcome, unsuccessful_outcome}
}

object downlink_nas_transport = {
    individual pcode : pcode_bits
    individual msg : message_enum
    individual mme_ue_s1ap_id : cid
    individual enb_ue_s1ap_id : cid
    individual nas_pdu : nas_pdu_string
    after init {
        pcode := 0;
        msg := message_enum.unsuccessful_outcome;
        mme_ue_s1ap_id := 0;
        enb_ue_s1ap_id := 0;
        nas_pdu := nas_pdu_string.0
    }

    action send(x:pcode_bits, y:message_enum, m:cid, e:cid, n:nas_pdu_string) = {
        pcode := x;
        msg := y;
        mme_ue_s1ap_id := m;
        enb_ue_s1ap_id := e;
        nas_pdu := n
    }

    action recv returns(y:message_enum) = {
        y := message_enum.successful_outcome if msg = message_enum.initial_message & 
               pcode = 11 & mme_ue_s1ap_id > 0 & enb_ue_s1ap_id > 0 & 
               nas_pdu ~= nas_pdu_string.0 else message_enum.unsuccessful_outcome
    }
}

import action ask returns (x:pcode_bits)
export action ask_and_check_pcode returns(ok:bool) = {
    ok := ask = 11
}

export downlink_nas_transport.send
export downlink_nas_transport.recv
